### ISSUE TITLE
Request related to general bibliography files

### ISSUE THREAD

**Issue by geritwagner** [whiskyechobravo/kerko#8]
I just discovered Kerko and would like to use this amazing tool. Unfortunately, my bibliography is not in Zotero. Would it be possible to use Kerko without Zotero, i.e., with a local bibliography file? I assume this should be relatively easy because there is no need for authentication. It may also make the tool attractive for more/different users. Would this suggestion be in line with your vision for the Kerko project?

**Comment by davidlesieur** [comment]
Glad you found Kerko of interest to your project! Unfortunately, Kerko could not easily be adapted to different back-ends because some of its key functions rely on Zotero's API, e.g., formatting citations with CSL, indexing the full-text of PDFs. Kerko is designed to build on top of Zotero as much as possible, and not to reinvent things that are already implemented in Zotero. Also, Kerko's data structures closely mirror Zotero's. Consequently, it would be out of scope for this project to accommodate other back-ends than Zotero. 

If your bibliography is using a known structured format, chances are it could be imported into Zotero relatively painlessly. If you have not used Zotero yet, I suggest that you give it a try. I have had clients who migrated to Zotero, and in the end they much preferred Zotero over their former systems.

**Comment by geritwagner** [comment]
Thank you for your response. Makes sense to rely on the Zotero indexing and formatting functionality. I concur that the import into Zotero shouldn't require too much effort. Keep up the good work on this exciting project!
